### ISSUE TITLE
FinalState Effect

### ISSUE THREAD

**Issue by isovector** [polysemy-research/polysemy-zoo#23]
```haskell
data FinalState s m a where
  GetFinal :: FinalState s m s

makeSem ''FinalState


runFinalState
    :: Member Fixpoint r
    => s
    -> Sem (State s ': FinalState s ': r) a
    -> Sem r a
runFinalState s m = mdo
  ~(s', a) <-
    interpret
      \case
        GetFinal -> pure s'
      (runLazyState s m)
  pure a
```

Get the final value of a state effect.

**Comment by KingoftheHomeless** [comment]
This actually becomes implementable once https://github.com/polysemy-research/polysemy/pull/187 is merged. In fact, an example implementation is part of the tests for that pull request.

**Comment by KingoftheHomeless** [comment]
This can be generalized to the following `Input` interpreter:

```haskell
------------------------------------------------------------------------------
-- | Runs an 'Input' effect by running a monadic action after the 'Sem' has
-- completed, and then providing the result to each request recursively.
runInputFixSem :: forall i r a
                . Member Fixpoint r
               => Sem r i
               -> Sem (Input i ': r) a
               -> Sem r a
runInputFixSem m sem = do
  rec
    a <- interpret (\Input -> pure i) sem
    i <- m
  return a
```

Such that:
```haskell
runFinalState :: Members '[State s, Fixpoint] r
              => Sem (FinalState s ': r) a
              -> Sem r a
runFinalState =
    runInputFixSem get
  . reinterpret (\GetFinal -> Input)
```

Is `runInputFixSem` worth adding to `polysemy` or `polysemy-zoo`?

**Comment by isovector** [comment]
whoa.

**Comment by KingoftheHomeless** [comment]
I'll take that as a "yes" 😄
I'll prepare a pull request for `polysemy-zoo`. With perhaps some other `Fixpoint` goodies...

**Comment by isovector** [comment]
how much easier would life be if there were only one repository?

**Comment by KingoftheHomeless** [comment]
I like `polysemy-zoo`. Lower barrier to entry for newcomers to contribute, a good place to put stuff we're unsure of or is just straight-up crazy, and we're a little less stringent about avoiding additional dependencies. Two "official" repos is a good thing to have, I feel.
