### ISSUE TITLE
Validation effect

### ISSUE THREAD

**Issue by jhenahan** [polysemy-research/polysemy-zoo#44]
https://hackage.haskell.org/package/monad-validate-1.1.0.0/docs/Control-Monad-Validate.html

Just a note for me to come back to. Could be a neat effect.

**Comment by ocharles** [comment]
This is an interesting one, as it's not currently expressible in `polysemy` due to have "non-standard" `<*>`.

**Comment by KingoftheHomeless** [comment]
This strikes me as though it should be possible. It would require some wrangling, but you could look at how `runError` is implemented, and then reimplement it using `ValidationT` instead of `ExceptT`.

**Comment by jhenahan** [comment]
Agreed that the morally questionable instances make this sort of sticky, but there may be some entertaining behavior to pull into something more lawful.
