### ISSUE TITLE
Excise `Final` from the zoo

### ISSUE THREAD

**Issue by jhenahan** [polysemy-research/polysemy-zoo#48]
@KingoftheHomeless Since `Final` is slated for the next `polysemy` release, it may be worthwhile to clear out conflicting definitions in the zoo, as well. I only even noticed the conflict because Nix yelled at me about an ambiguous occurrence of `Final` when it was trying to build the latest of both.

**Comment by KingoftheHomeless** [comment]
This is what #46 will do.

**Comment by jhenahan** [comment]
Oh, totally missed that. Thanks!
