### ISSUE TITLE
Haddock for v0.6 broken

### ISSUE THREAD

**Issue by KingoftheHomeless** [polysemy-research/polysemy-zoo#50]
Documentation on Hackage is broken. When I build the docs on my machine, it complains that it can't find `Polysemy.Plugin`. Disabling the plugin when generating the docs fixes it on my end,
but I'm not sure if it's the same issue on Hackage's side, or why it only crops up now.

**Comment by isovector** [comment]
It's the same issue; I always have to manually push haddocks for this project.

**Comment by isovector** [comment]
https://github.com/haskell/haddock/issues/900

**Comment by isovector** [comment]
Pushed

**Comment by KingoftheHomeless** [comment]
Oh, ok then I get it. Thanks.
