### ISSUE TITLE
working ghc 9.2 hackage release (ghc-prim bump required)

### ISSUE THREAD

**Issue by ruby0b** [polysemy-research/polysemy-zoo#78]
The current hackage release has too restrictive constraints.
ghc-prim still needs to be bumped to v0.8, otherwise master builds just fine.

**Comment by jlwoodwa** [comment]
Isn't `compact` an issue as well? `compact-0.2.0.0` doesn't support `base>=4.16`.

**Comment by ruby0b** [comment]
correct, it works fine when using the latest commit, I've opened an issue:
https://github.com/ezyang/compact/issues/20

**Comment by spacekitteh** [comment]
@isovector is it possible to put out a new release?

**Comment by KingoftheHomeless** [comment]
I'm the right man to ping about this, me or @tek, really. I'll look into a release during the weekend.

**Comment by tek** [comment]
I don't have access to Hackage for zoo as far as I can tell!

**Comment by KingoftheHomeless** [comment]
_What_
I'll have to fix that!

**Comment by tek** [comment]
released
